"""create V1 persistence tables

Revision ID: 7f53c0c7be74
Revises:
Create Date: 2026-09-09 13:09:49.561896

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7f53c0c7be74"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crop_passports",
        sa.Column("passport_id", sa.String(length=100), nullable=False),
        sa.Column("farmer_id", sa.String(length=100), nullable=False),
        sa.Column("crop_id", sa.String(length=100), nullable=False),
        sa.Column("plot_ref", sa.String(length=100), nullable=False),
        sa.Column("current_stage", sa.String(length=100), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("passport_id"),
        sa.UniqueConstraint(
            "farmer_id", "crop_id", "plot_ref", name="uq_crop_passports_farmer_crop_plot"
        ),
    )
    op.create_table(
        "history_events",
        sa.Column("event_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("farmer_id", sa.String(length=100), nullable=False),
        sa.Column("crop_id", sa.String(length=100), nullable=False),
        sa.Column("crop_family", sa.String(length=100), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("recommendation_id", sa.String(length=100), nullable=True),
        sa.Column("trace_id", sa.String(length=100), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        "ix_history_events_farmer_crop_recorded",
        "history_events",
        ["farmer_id", "crop_id", "recorded_at"],
        unique=False,
    )
    op.create_index(
        "ix_history_events_farmer_family_recorded",
        "history_events",
        ["farmer_id", "crop_family", "recorded_at"],
        unique=False,
    )
    op.create_table(
        "sms_deliveries",
        sa.Column("delivery_id", sa.String(length=100), nullable=False),
        sa.Column("recipient_id", sa.String(length=100), nullable=False),
        sa.Column("crop_id", sa.String(length=100), nullable=False),
        sa.Column("recommendation_id", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("delivery_id"),
    )
    op.create_index(
        "ix_sms_deliveries_recipient_delivered",
        "sms_deliveries",
        ["recipient_id", "delivered_at"],
        unique=False,
    )
    op.create_table(
        "trace_records",
        sa.Column("trace_id", sa.String(length=100), nullable=False),
        sa.Column("request_id", sa.String(length=100), nullable=False),
        sa.Column("crop_id", sa.String(length=100), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("final_recommendation_id", sa.String(length=100), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("trace_id"),
    )
    op.create_table(
        "recommendations",
        sa.Column("recommendation_id", sa.String(length=100), nullable=False),
        sa.Column("request_id", sa.String(length=100), nullable=False),
        sa.Column("crop_id", sa.String(length=100), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("trace_id", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["trace_id"], ["trace_records.trace_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("recommendation_id"),
        sa.UniqueConstraint("trace_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recommendations")
    op.drop_table("trace_records")
    op.drop_index("ix_sms_deliveries_recipient_delivered", table_name="sms_deliveries")
    op.drop_table("sms_deliveries")
    op.drop_index("ix_history_events_farmer_family_recorded", table_name="history_events")
    op.drop_index("ix_history_events_farmer_crop_recorded", table_name="history_events")
    op.drop_table("history_events")
    op.drop_table("crop_passports")
    # ### end Alembic commands ###
